// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC72D12oiyc8eLlyJA7o1ngbp1AzgbAV2c',
    appId: '1:325064629125:web:907719d73be9e895a782ec',
    messagingSenderId: '325064629125',
    projectId: 'labour-managment-cf247',
    authDomain: 'labour-managment-cf247.firebaseapp.com',
    storageBucket: 'labour-managment-cf247.appspot.com',
    measurementId: 'G-144LYZVGZ0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBhnu1K0USbhPdk9MlY8BAwvsTFlGoHZPU',
    appId: '1:325064629125:android:42d223a740af0f5fa782ec',
    messagingSenderId: '325064629125',
    projectId: 'labour-managment-cf247',
    storageBucket: 'labour-managment-cf247.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC99iC-frGTq4ue5AOv56iT8SwJQjf2EpE',
    appId: '1:325064629125:ios:f85386547f7acadda782ec',
    messagingSenderId: '325064629125',
    projectId: 'labour-managment-cf247',
    storageBucket: 'labour-managment-cf247.appspot.com',
    iosBundleId: 'com.example.laborManagment',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC99iC-frGTq4ue5AOv56iT8SwJQjf2EpE',
    appId: '1:325064629125:ios:f85386547f7acadda782ec',
    messagingSenderId: '325064629125',
    projectId: 'labour-managment-cf247',
    storageBucket: 'labour-managment-cf247.appspot.com',
    iosBundleId: 'com.example.laborManagment',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC72D12oiyc8eLlyJA7o1ngbp1AzgbAV2c',
    appId: '1:325064629125:web:ace8833f7d2c2903a782ec',
    messagingSenderId: '325064629125',
    projectId: 'labour-managment-cf247',
    authDomain: 'labour-managment-cf247.firebaseapp.com',
    storageBucket: 'labour-managment-cf247.appspot.com',
    measurementId: 'G-C9T095MQZ6',
  );
}
